import 'package:flutter/material.dart';

class AppConstants {
  static const String appName = 'MessMate & Finance';

  // Changed to keys for localization
  static const List<String> categories = [
    'income',
    'expense',
    'transfer',
    'market',
    'total',
  ];

  static const List<String> accountTypes = [
    'cash',
    'bank',
    'mobile_banking',
    'credit_card',
  ];

  static const List<String> units = [
    'kg',
    'liter',
    'piece',
    'meter',
    'dozen',
    'katha',
  ];

  static const List<Color> noteColors = [
    Color(0xFFFFF3E0),
    Color(0xFFE8F5E9),
    Color(0xFFE3F2FD),
    Color(0xFFFCE4EC),
    Color(0xFFF3E5F5),
    Color(0xFFE0F2F1),
  ];
}

class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'app_name': 'Finance Manager',
      'home': 'Home',
      'accounts': 'Accounts',
      'reports': 'Reports',
      'notes': 'Notes',
      'settings': 'Settings',
      'profile': 'Profile',
      'income': 'Income',
      'expense': 'Expense',
      'transfer': 'Transfer',
      'market': 'Market',
      'total': 'Total',
      'balance': 'Balance',
      'add': 'Add',
      'edit': 'Edit',
      'delete': 'Delete',
      'save': 'Save',
      'cancel': 'Cancel',
      'login': 'Login',
      'signup': 'Sign Up',
      'logout': 'Logout',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'forgot_password': 'Forgot Password?',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'system_mode': 'System Mode',
      'language': 'Language',
      'currency': 'Currency',
      'security': 'Security',
      'pin_lock': 'PIN Lock',
      'biometric': 'Biometric',
      'notifications': 'Notifications',
      'unlock_with_biometrics': 'Unlock with biometrics',
      'incorrect_pin': 'Incorrect PIN',
      'enter_pin_to_unlock': 'Enter PIN to unlock',
      'use_biometrics': 'Use biometrics',
      'cash': 'Cash',
      'bank': 'Bank',
      'mobile_banking': 'Mobile Banking',
      'credit_card': 'Credit Card',
      'kg': 'Kg',
      'liter': 'Liter',
      'piece': 'Piece',
      'meter': 'Meter',
      'dozen': 'Dozen',
      'katha': 'Katha',
      'total_balance': 'Total Balance',
      'quick_add': 'Quick Add',
      'market_list': 'Market List',
      'convert_to_expense': 'Convert to Expense',
    },
    'bn': {
      'app_name': 'ফাইন্যান্স ম্যানেজার',
      'home': 'হোম',
      'accounts': 'অ্যাকাউন্ট',
      'reports': 'রিপোর্ট',
      'notes': 'নোট',
      'settings': 'সেটিংস',
      'profile': 'প্রোফাইল',
      'income': 'আয়',
      'expense': 'ব্যয়',
      'transfer': 'ট্রান্সফার',
      'market': 'বাজার',
      'total': 'মোট',
      'balance': 'ব্য্যালেন্স',
      'add': 'যোগ করুন',
      'edit': 'সম্পাদনা',
      'delete': 'মুছুন',
      'save': 'সংরক্ষণ',
      'cancel': 'বাতিল',
      'login': 'লগইন',
      'signup': 'নিবন্ধন',
      'logout': 'লগআউট',
      'email': 'ইমেইল',
      'password': 'পাসওয়ার্ড',
      'confirm_password': 'পাসওয়ার্ড নিশ্চিত করুন',
      'forgot_password': 'পাসওয়ার্ড ভুলে গেছেন?',
      'dark_mode': 'ডার্ক মোড',
      'light_mode': 'লাইট মোড',
      'system_mode': 'সিস্টেম মোড',
      'language': 'ভাষা',
      'currency': 'মুদ্রা',
      'security': 'নিরাপত্তা',
      'pin_lock': 'পিন লক',
      'biometric': 'বায়োমেট্রিক',
      'notifications': 'নোটিফিকেশন',
      'unlock_with_biometrics': 'বায়োমেট্রিক দিয়ে আনলক করুন',
      'incorrect_pin': 'ভুল পিন',
      'enter_pin_to_unlock': 'আনলক করতে পিন লিখুন',
      'use_biometrics': 'বায়োমেট্রিক ব্যবহার করুন',
      'cash': 'ক্যাশ',
      'bank': 'ব্যাংক',
      'mobile_banking': 'মোবাইল ব্যাংকিং',
      'credit_card': 'ক্রেডিট কার্ড',
      'kg': 'কেজি',
      'liter': 'লিটার',
      'piece': 'পিস',
      'meter': 'মিটার',
      'dozen': 'ডজন',
      'katha': 'কোথা',
      'total_balance': 'মোট ব্যালেন্স',
      'quick_add': 'দ্রুত যোগ করুন',
      'market_list': 'বাজার তালিকা',
      'convert_to_expense': 'খরচে রূপান্তর',
    },
  };
}
